kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# name: kubernetes-lab
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.configs."registry:5000".tls]
    insecure_skip_verify = true
    ca_file = ""
    cert_file = ""
    key_file = ""
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry:5000"]
    endpoint = ["http://registry:5000"]
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry"]
    endpoint = ["http://registry:5000"]
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost"]
    endpoint = ["http://registry:5000"]

nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=2Gi
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=3Gi
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=3Gi
