kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# name: kubernetes-lab
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri"."registry:5000"]
    insecure_skip_verify = true
    ca_file = ""
    cert_file = ""
    key_file = ""
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=2Gi
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=3Gi
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=3Gi
